### ISSUE TITLE
ethicity group

### ISSUE THREAD

**Issue by Lhemamou** [BiDAlab/FairCVtest#1]
Hello,

I am trying to expand your toy dataset with other protected attributes. Could you define more precisely what groups match with specific index ? (G0=white, G1=hispanic, etc ?)

Thanks !

**Comment by AlejandroPenna** [comment]
Hi Lhemamou,

The FairCVdb database is based on our DiveFace database, thus the ethnicity groups are those defined there. More concretely, G1 refers to people with ancestral origins in Japan, China and Korea, G2 refers to people with ancetral origins in Sub-Saharan Africa, India, Bangladesh and Butan, and finally G3 covers peoples with ancestral origins in Europe, North America and Latin-America. We included and image_list attribute with the names of the pics used to extract each face embedding. If you have further questions about the demographics of FairCV, please let us know, or check the original DiveFace reference (https://arxiv.org/ftp/arxiv/papers/1902/1902.00334.pdf). Thank you!

**Comment by Lhemamou** [comment]
Thanks you for all the information !
